on:
    push:
      branches:
        - main
  
jobs:
    first_job:
        runs-on: windows-latest

        steps:
            - run: flutter pub get
        # - run: flutter test integration_test



        # - uses: actions/checkout@v4

        # - uses: futureware-tech/simulator-action@v3
        #     with:
        #     model: 'iPhone 14'

        # - uses: subosito/flutter-action@v2
        #     with:
        #     channel: 'stable'