on:
    push:
      branches:
        - main
  

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

    #   - uses: futureware-tech/simulator-action@v3
    #     with:
    #       model: 'iPhone 14'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
            name: windowsTest-app
            path: build\windows\x64\runner\Release
        # name: windows-app
        # path: build/windows/runner/Release
            
        